name: smartbill_plus
description: A mobile app to display Megaflex Gen tariff rates using offline CSV
publish_to: 'none' # Prevent publishing to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/tariff_details.csv
    - assets/eskom_logo.png
    - assets/eskom_icon.png
    - assets/1159364720.csv
    - assets/9857665714.csv
    - assets/7614718533.csv
    - assets/5717941398.csv

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/eskom_icon.png"

